import json
 
# List of commands:
list_read = [
"HR_read_device_type_fxn",
"HR_read_sw_version_fxn",
"HR_read_factory_number_fxn",
"HR_read_production_year_fxn",
"HR_read_production_month_fxn",
"HR_read_production_day_fxn",
"HR_read_slave_id_fxn",
"HR_read_rs485_baudrate_fxn",
"HR_read_ext_settings_fxn",
"HR_read_uv_settings_fxn",
"HR_read_uv_fault_counter_fxn",
"HR_read_uv_test_interval_fxn",
"HR_read_ir_settings_fxn",
"HR_read_ir_fault_counter_fxn",
"HR_read_ir_test_interval_fxn",
"HR_read_ind_rel_auto_settings_fxn",
"HR_read_fire_alarm_delay_fxn",
"HR_read_auto_heat_settings_fxn",
"HR_read_sensor_heating_power_fxn",
"HR_read_sensor_heating_temperature_fxn",
"HR_read_pwm_interface_current_fxn",
"HR_read_input_power_voltage_fxn",
"HR_read_device_temperature_fxn",
"HR_read_device_status1_fxn",
"HR_read_device_status2_fxn",
"HR_read_device_status3_fxn",
"HR_read_indicator_mode_fxn",
"HR_read_uv_pps_fxn",
"HR_read_ir_energy_fxn",
"HR_read_ir_sensor1_level_fxn",
"HR_read_uv_sensor1_level_fxn",
"HR_read_calibration_status_fxn",
"HR_read_is_not_allowed_fxn",
"HR_read_year_fxn",
"HR_read_month_day_fxn",
"HR_read_hour_minute_fxn",
"HR_read_second_fxn",
"HR_read_is_not_allowed_fxn",
"HR_read_is_not_allowed_fxn",
"HR_read_is_not_allowed_fxn",
"HR_read_is_not_allowed_fxn",
"HR_read_reg_accept_data_by_pswd_fxn",
"HR_read_event_log_reg_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_event_year_fxn",
"HR_read_event_month_day_fxn",
"HR_read_event_hour_minute_fxn",
"HR_read_event_sec_hundredth_sec_fxn",
"HR_read_event_code_fxn",
"HR_read_event_status_code_fxn",
"HR_read_event_temperature_fxn",
"HR_read_event_voltage_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_setup_year_fxn",
"HR_read_setup_month_day_fxn",
"HR_read_setup_hour_minute_fxn",
"HR_read_setup_sec_hundredth_sec_fxn",
"HR_read_setup_code_fxn",
"HR_read_setup_prev_value_hi_fxn",
"HR_read_setup_prev_value_lo_fxn",
"HR_read_setup_new_value_hi_fxn",
"HR_read_setup_new_value_lo_fxn",
"HR_read_setup_result_fxn",
"HR_read_reserve_fxn"
]

list_write = [
"HR_write_device_type_fxn",
"HR_write_sw_version_fxn",
"HR_write_factory_number_fxn",
"HR_write_production_year_fxn",
"HR_write_production_month_fxn",
"HR_write_production_day_fxn",
"HR_write_slave_id_fxn",
"HR_write_rs485_baudrate_fxn",
"HR_write_ext_settings_fxn",
"HR_write_uv_settings_fxn",
"HR_write_uv_fault_counter_fxn",
"HR_write_uv_test_interval_fxn",
"HR_write_ir_settings_fxn",
"HR_write_ir_fault_counter_fxn",
"HR_write_ir_test_interval_fxn",
"HR_write_ind_rel_auto_settings_fxn",
"HR_write_fire_alarm_delay_fxn",
"HR_write_auto_heat_settings_fxn",
"HR_write_sensor_heating_power_fxn",
"HR_write_sensor_heating_temperature_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_ctrl_commands_fxn",
"HR_write_year_fxn",
"HR_write_month_day_fxn",
"HR_write_hour_minute_fxn",
"HR_write_second_fxn",
"HR_write_pswd_cfg_fxn",
"HR_write_pswd_const_dbg_fxn",
"HR_write_reg_change_pswd_cfg_fxn",
"HR_write_reg_change_pswd_const_dbg_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_event_log_reg_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_is_not_allowed_fxn",
"HR_write_dbg_commands_reg_fxn"
]

# make dictionary
list_out = []
len_cmd = 1
name = ""
vl_type = "UINT16_T"
i_list = 0
n_reg = 40001
addr_cmd = 0
while n_reg < 40302:
    if ((n_reg >= 40008 and n_reg <= 40010) 
        or (n_reg >= 40014 and n_reg <= 40015)
        or (n_reg >= 40019 and n_reg <= 40020)
        or (n_reg >= 40024 and n_reg <= 40026)
        or (n_reg >= 40032 and n_reg <= 40033)
        or (n_reg >= 40044 and n_reg <= 40045)
        or (n_reg >= 40053 and n_reg <= 40059)
        or (n_reg >= 40091 and n_reg <= 40099)
        or (n_reg >= 40181 and n_reg <= 40200)):
        name = "HR_read_reserve_fxn"
        len_cmd = 1
        vl_type = "UINT16_T"
    elif (n_reg >= 40003 and n_reg <= 40004 ):
        name = list_read[i_list]
        if n_reg == 40004:
            i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    elif (n_reg >= 40060 and n_reg <= 40064 ):
        HR_read_is_not_allowed_fxn = "HR_read_is_not_allowed_fxn"
        name = list_read[i_list]
        if n_reg == 40064:
            i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    elif (n_reg >= 40065 and n_reg <= 40074 ):
        HR_read_is_not_allowed_fxn = "HR_read_is_not_allowed_fxn"
        name = list_read[i_list]
        if n_reg == 40074:
            i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    elif (n_reg >= 40075 and n_reg <= 40079 ):
        HR_read_is_not_allowed_fxn = "HR_read_is_not_allowed_fxn"
        name = list_read[i_list]
        if n_reg == 40079:
            i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    elif (n_reg >= 40080 and n_reg <= 40089 ):
        HR_read_is_not_allowed_fxn = "HR_read_is_not_allowed_fxn"
        name = list_read[i_list]
        if n_reg == 40089:
            i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    else:
        name = list_read[i_list]
        i_list += 1
        len_cmd = 1
        vl_type = "UINT16_T"
    
    addr_cmd = n_reg - 40000
    print("№ reg: "+str(addr_cmd)+" Cmd: "+name)
    dict_read_cmd = {
        "address": addr_cmd,
        "len": len_cmd,
        "name": name,
        "value_type": vl_type
        }  
    list_out.append(dict_read_cmd)
    n_reg += 1

dict_out = {
    "Holding Registers": list_out
}

# Serializing json
json_object = json.dumps(dict_out, indent=4)
 
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)
    
